/*
 * This Java source file was generated by the Gradle 'init' task.
 */
// package latXMLQuery;
package latXMLQuery;

import main.java.latXMLQuery.QueryXMLFileDemo;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        QueryXMLFileDemo queryXMLFileDemo = new QueryXMLFileDemo();
        queryXMLFileDemo.QueryXMLFileDemoTest();      
    }
}
