/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package latJSONEncoding;

import main.java.latJSONEncoding.JsonEncodeDemo;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        JsonEncodeDemo jsonEncodeDemo = new JsonEncodeDemo();
        jsonEncodeDemo.jsonEncodeDemoTest();
    }
}
