/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package latCRCInventory;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());

        // Show Barang
        Barang oBarang = new Barang();
        oBarang.showBarang();

        // Show Supplier
        Supplier oSupplier = new Supplier();
        oSupplier.showSupplier();

        //Show Pengadaan
        Pengadaan oPengadaan = new Pengadaan();
        oPengadaan.showPengadaan();
    }
}
