/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package latJUnit2;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test
    void junitTestAdder(){
        TestAdder testAdder = new TestAdder();
        testAdder.testSumPositiveNumbersOneAndOne();
        testAdder.testSumPositiveNumbersOneAndTwo();
        testAdder.testSumPositiveNumbersTwoAndTwo();
        testAdder.testSumZeroNeutral();
        testAdder.testSumNegativeNumbers();
        testAdder.testSumPositiveAndNegative();
        testAdder.testSumLargeNumbers();
    }
}
