/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package latihanCreateThread;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());

        // dg. Ini adalah untuk create thread menggunakan interface Runnable
        System.out.println("Ini adalah untuk create thread menggunakan interface Runnable");
        HelloRunnable helloRunnable = new HelloRunnable();
        helloRunnable.helloRunnableFirst();

        // dg. Ini adalah untuk create thread menggunakan class Thread
        System.out.println("Ini adalah untuk create thread menggunakan class Thread");
        HelloThread helloThread = new HelloThread();
        helloThread.helloThreadFirst();
    }
}
