/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package latJUnit1;

import org.junit.jupiter.api.Test;

import jdk.internal.jline.internal.TestAccessible;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    /*
    @Test
    void junitTestAdder(){
        TestAdder testAdder = new TestAdder();
        testAdder.testSumPositiveNumbersOneAndOne();
        testAdder.testSumPositiveNumbersOneAndTwo();
        testAdder.testSumPositiveNumbersTwoAndTwo();
        testAdder.testSumZeroNeutral();
        testAdder.testSumNegativeNumbers();
        testAdder.testSumPositiveAndNegative();
        testAdder.testSumLargeNumbers();
    }
    */
}
