/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lat1Bycle;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());

        /**
         * Program ini adalah untuk mengakses method2 baik dari class tersebut, yaitu MountainBike
         * maupun method dari superclassnya yaitu clas bicycle
         */

         int pstartHeight = 10;
         int pstartCadence = 20;
         int pstartSpeed = 30;
         int pstartGear = 40;
         MountainBike mountainBike = new MountainBike(pstartHeight, pstartCadence, pstartSpeed, pstartGear);
         System.out.println("Tinggi awal : " + mountainBike.seatHeight );
         System.out.println("Cadence awal : " + mountainBike.cadence );
         System.out.println("Kecepatan awal : " + mountainBike.speed );
         System.out.println("Gear awal : " + mountainBike.gear );

         mountainBike.setHeight(10);
         mountainBike.setCadence(10);
         mountainBike.setGear(10);
         mountainBike.applyBrake(10);
         mountainBike.speedUp(10);
         
         System.out.println("========");
         System.out.println("Tinggi sekarang : " + mountainBike.seatHeight );
         System.out.println("Cadence sekarang : " + mountainBike.cadence );
         System.out.println("Kecepatan sekarang : " + mountainBike.speed );
         System.out.println("Gear sekarang : " + mountainBike.gear );

         
    }
}
