/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package latXML1;

import main.java.latXML1.DomParserDemo;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        DomParserDemo domParserDemo = new DomParserDemo();
        domParserDemo.DomParserDemoTest();

    }
}
