/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package latihanAdapterPattern;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());

      // dg. Ini adalah implementasi dari AdapterPatternDemo.java
      // Adapter Pattern merupakan Structural Design Pattern.
      // Adapter Pattern digunakan untuk men-struktur class, dimana class ini meng-implementasi
      // 2 buah interface yang saling tidak compatible, tapi dapat saling bekerjasama nantinya.
      // Contohnya disini adalah membuat audioplayer dari 2 buah interface, yaitu interface MediaPlayer
      // dan interface AdvanceMediaPlayer. Pada audioPlayer (yang built in nya untuk mp3)
      // ditambahkan class MediaPlayer sebagai penambahan fasilitas/support untuk 
      // AdvanceMediaPlayer, yang dpt mensupport untuk mem-play mp4 dan vlc

        AudioPlayer audioPlayer = new AudioPlayer();

      audioPlayer.play("mp3", "beyond the horizon.mp3");
      audioPlayer.play("mp4", "alone.mp4");
      audioPlayer.play("vlc", "far far away.vlc");
      audioPlayer.play("avi", "mind me.avi");
    }
}
