/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package latFunctionalInterface;

import latFunctionalInterface.MyInterfaceImplementation;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());

        // dg. Ini adalah contoh interface yg dpt dijadikan functional programming,
        // karena di dlm interface tersebut hanya ada 1 method saja.
        MyInterfaceImplementation myInterfaceImplementation = new MyInterfaceImplementation();
        myInterfaceImplementation.run();

        // dg. Ini adalah contoh interface yg dapat dijadikan functinal programming,
        // karena di dalam interface tersebut, meskipun terdapat total 3 method, tetapi
        // cuman ada 1 method saja yg belum diimplementasikan.
        MyInterface2Implementation myInterface2Implementation = new MyInterface2Implementation();
        myInterface2Implementation.run();
    }
}
