/*
 * This Java source file was generated by the Gradle 'init' task.
 */

/**
 * Program ini adalah untuk mengimplementasikan annotasi override
 * @author Dedi Gunawan
 * 
 */
package latAnnotation;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());

        int x;
        Derived obj = new Derived();
        obj.display();
    }
}
