/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package latPureFunction;

import main.java.latPureFunction.ObjectWithPureFunction;
import main.java.latPureFunction.ObjectWithNonPureFunction;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        
        // dg. Ini adalah contoh pure function. Semua variable adalah di dalam function tsb,
        // tidak ada variable yang digunakan dari global variable. 
        ObjectWithPureFunction objectWithPureFunction = new ObjectWithPureFunction();
        System.out.println(objectWithPureFunction.sum(3, 4));

        // dg. Ini adalah contoh non pure function, dimana method tsb menggunakan global variable
        // dalam pemrosesannya. Hal ini dihindari dan bukan termasuk functional programming.
        ObjectWithNonPureFunction objectWithNonPureFunction = new ObjectWithNonPureFunction();
        System.out.println( objectWithNonPureFunction.add(1) );



    }
}
