/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package latihanBridgePattern;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());

      // dg. Ini adalah implementasi dari BridgePatternDemo.java
      // Bridge Pattern digunakan untuk membagi 1 buah interface menjadi 2 class yg saling
      // independent.
      // Pada contoh ini, digunakan untuk membagi interface DrawAPI menjadi 2 class untuk
      // GreenCircle.java dan RedCircle.java

      Shape redCircle = new Circle(100,100, 10, new RedCircle());
      Shape greenCircle = new Circle(100,100, 10, new GreenCircle());

      redCircle.draw();
      greenCircle.draw();
    }
}
