/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lat3ATM;

import lat3ATM.ATMTransaction;

public class App {

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());

        ATMTransaction atmTransaction = new ATMTransaction();
        atmTransaction.ATMOption();
    }
}
