/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package latSerDeserJavaObject;

import main.java.latSerDeserJavaObject.SerialExample;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        SerialExample serialExample = new SerialExample();
        serialExample.serialExampleTest();
    }
}
