/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package latNoState;
import latNoState.Calculator;
import latNoState.CalculatorState;      

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());

        // dg. Ini adalah contoh untuk no state (masuk kategori functional programming)
        Calculator calculator = new Calculator();
        System.out.println( calculator.sum(4, 5));

        // dg. Ini adalah contoh untuk state (tidak masuk kategori functional programming)
        CalculatorState calculatorState = new CalculatorState();
        System.out.println( calculatorState.sum(5) );
        
    }
}
                                                                                                      
