/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lat2ArrayExist;

import lat2ArrayExist.Array_exists;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());

        // dg. Ini untuk fungsi Array exists pada Functional java
        System.out.println("Ini untuk fungsi Array exists pada Functional Java. ");       
        Array_exists array_exists = new Array_exists();
        array_exists.Array_exists_test();
        System.out.println("=========");

        // dg. Ini untuk fungsi Array filter pada Functional java
        System.out.println("Ini untuk fungsi Array filter pada Functional Java. "); 
        Array_filter array_filter = new Array_filter();
        array_filter.Array_filter_test();
        System.out.println("=========");

        // dg. Ini untuk fungsi Array foldLeft pada Functional java
        System.out.println("Ini untuk fungsi Array foldLeft pada Functional Java. "); 
        Array_foldLeft array_foldLeft = new Array_foldLeft();
        array_foldLeft.Array_foldLeft_test();
        System.out.println("=========");
    }
}
