/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package latXMLCreate;

import main.java.latXMLCreate.CreateXMLFileDemo;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        CreateXMLFileDemo createXMLFileDemo = new CreateXMLFileDemo();
        createXMLFileDemo.CreateXMLFileDemoTest();
    }
}
