/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package latXMLModify;

import main.java.latXMLModify.ModifyXmlFileDemo;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        ModifyXmlFileDemo modifyXmlFileDemo = new ModifyXmlFileDemo();
        modifyXmlFileDemo.ModifyXmlFileDemoTest();
    }
}
