/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package latihanFactoryPattern;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());

        // dg. Mengimplementasi FactoryPatternDemo.java
        // Jadi pada bagian ini adalah dengan membuat object dari class ShapeFactory,
        // karena pada class ShapeFactory ini akan dibuatkan object yg sebenarnya 
        // dari object yg dibutuhkan oleh aplikasi. Ada 3 type : circle, rectangle dan square
        // object yg sebenarnya adalah dari method getShape()
        ShapeFactory shapeFactory = new ShapeFactory();

        //get an object of Circle and call its draw method.
        Shape shape1 = shapeFactory.getShape("CIRCLE");
  
        //call draw method of Circle
        shape1.draw();
  
        //get an object of Rectangle and call its draw method.
        Shape shape2 = shapeFactory.getShape("RECTANGLE");
  
        //call draw method of Rectangle
        shape2.draw();
  
        //get an object of Square and call its draw method.
        Shape shape3 = shapeFactory.getShape("SQUARE");
  
        //call draw method of square
        shape3.draw();
    }
}
